services:
    _defaults:
        autowire: true

    Datana\Zendesk\Api\TicketsApi: null
    Datana\Zendesk\Api\NullTicketsApi: null
    Datana\Zendesk\Api\TicketsApiInterface: '@Datana\Zendesk\Api\TicketsApi'

    Datana\Zendesk\Api\AttachmentsApi: null
    Datana\Zendesk\Api\NullAttachmentsApi: null
    Datana\Zendesk\Api\AttachmentsApiInterface: '@Datana\Zendesk\Api\AttachmentsApi'


when@prod:
    services:
        Datana\Zendesk\Api\TicketsApiInterface: '@Datana\Zendesk\Api\TicketsApi'
        Datana\Zendesk\Api\AttachmentsApiInterface: '@Datana\Zendesk\Api\AttachmentsApi'

when@dev:
    services:
        Datana\Zendesk\Api\TicketsApiInterface: '@Datana\Zendesk\Api\NullTicketsApi'
        Datana\Zendesk\Api\AttachmentsApiInterface: '@Datana\Zendesk\Api\NullAttachmentsApi'

when@test:
    services:
        Datana\Zendesk\Api\TicketsApiInterface: '@Datana\Zendesk\Api\NullTicketsApi'
        Datana\Zendesk\Api\AttachmentsApiInterface: '@Datana\Zendesk\Api\NullAttachmentsApi'
